config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  get '/users/edit' => 'users#edit', :as => :edit_user
  resources :users, :except => [:edit]
  
  resources :categories
  resources :products do
    resources :comments 
  end
  

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_many :users, :through => :products

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  product_id :integer
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Comment < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  image       :text
#  price       :float
#  size        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  description :text
#

class Product < ActiveRecord::Base
	  belongs_to :user
  	has_many :comments
  	has_and_belongs_to_many :categories
  	
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  description     :text
#  status          :string(255)
#  city            :string(255)
#  country         :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  email           :string(255)
#  password_digest :string(255)
#  avatar          :text             default("avatar.jpg")
#

class User < ActiveRecord::Base
	has_secure_password
	
    has_many :products
    has_many :categories, :through => :products
    has_many :comments 
    

  	validates :name, :presence => true, :uniqueness => true, :length => {:minimum => 2}
  	validates :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  private
  def authenticate
    @current_user = User.find_by(:id => session[:user_id])
    session[:user_id] = nil unless @current_user.present?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
  end

  def update
    @category.products = Product.find params[:id]
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
    end

    def show
        @comment = Comment.find params[:id]
    end

    def new
        @comment = Comment.new
    end

    def create
        product.comments.create(comment_params) do |comment|
            comment.user_id = @current_user.id
        end
        redirect_to product_path(@product)

        # respond_to do |format|
        #     if @comment.save
        #         format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        #         format.json { render action: 'show', status: :created, location: @comment }
        #     else
        #         format.html { render action: 'new' }
        #         format.json { render json: @comment.errors, status: :unprocessable_entity }
        #     end
        # end
    end

    def upvote
        @product = Product.find(params[:product_id])
        @comment = @product.comments.find(params[:id])
        @comment.liked_by @current_user

        redirect_to @product
    
    end


    def edit
        @comment = Comment.find params[:id]
    end

    def update
        comment = Comment.find params[:id]
        comment.update comment_params
        redirect_to product_path(@product)
    end

    def destroy
        comment = Comment.find params[:id]
        comment.destroy
        redirect_to product_path(@product)
    end

    private

    def comment_params
        params.require(:comment).permit(:user_id, :body, :product_id)
    end

    def product
        @product = Product.find(params[:product_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index 
		@products = Product.all
	end

	def show
    @users = User.all
		@product = Product.find params[:id]
	end

  def new
    @product = Product.new
  end

  def create
    product = Product.new product_params
    product.user_id = @current_user.id
    product.save
    redirect_to product 
  end


  def edit
    @product = Product.find params[:id]
  end

  def update
    product = Product.find params[:id]
    product.update product_params
    redirect_to product
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:title, :price, :size, :description,  :image, :user_id, :category_ids => [], :comments => [])
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # Login form
  def new
  end

  # Where the login form POSTs data
  def create
    user = User.where(:name => params[:username]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  # Logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    user = @current_user
    user.update user_params
    redirect_to user
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require(:user).permit(:name, :status, :city, :country, :email, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def intellinav
    nav = ''
    if @current_user.present?
      nav += "<li>Hello #{ @current_user.name }</li> "
      nav += "<li>" + link_to('Users', users_path) + "</li> "
      nav += "<li>" + link_to('Profile', user_path(@current_user)) + "</li> "
      nav += "<li>#{ link_to('Sign out', login_path, :method => :delete, :data => {:confirm => 'Are you sure?'}) }</li> "
      nav += "<li>" + link_to('Add Item', new_product_path) + "</li> "
    else
      nav += "<li>#{ link_to('Sign up', new_user_path) }</li> "
      nav += "<li>#{ link_to('Sign in', login_path) }</li>"
    end
    nav
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/index.haml
.category
  .category_image.one
  .category_image.two
  .category_image.three

.lists
  %h2 Categories
  %ul
  - @categories.each do |category|
    %li= link_to category.name, category

.category    
  .category_image.four
  .category_image.five
  .category_image.six

app/views/categories/show.haml
.show_all
  .head
    %h2= @category.name

  %ul
  - @category.products.each do |product|
    .inside_product   
      %li= link_to product.title, product
      .special
        = link_to image_tag(product.image), product

  %p
    .linking_button
      = link_to('All categories', categories_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Charisma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav class='main_nav'>
      <ul>
        <li><%= link_to('Home', root_path) %></li>
        <li><%= link_to('Categories', categories_path) %></li>
        <li><%= link_to('Products', products_path) %></li>
      </ul>
      
    <div class="user_nav">
      <%== intellinav %>
    </div>
  </nav>
</header>
<div class="container main">
  <%= yield %>
</div>

<footer>&copy; 2014 T.Butenko </footer>



</body>
</html>

app/views/pages/home.html.erb
<div class="main_page">
    <img class='main_page_photo' src='assets/main1.jpg'>
    <img class='main_page_photo' src='assets/main2.jpg'>
    <img class='main_page_photo' src='assets/main3.jpg'>
    <img class='main_page_photo' src='assets/main4.jpg'>
    <img class='main_page_photo' src='assets/main5.jpg'>
    <img class='main_page_photo' src='assets/main6.jpg'>
    <img class='main_page_photo' src='assets/main7.jpg'>
    <img class='main_page_photo' src='assets/main8.jpg'>
    <img class='main_page_photo' src='assets/main9.jpg'>
    <img class='main_page_photo' src='assets/main10.jpg'>
    <img class='main_page_photo' src='assets/main11.jpg'>
    <img class='main_page_photo' src='assets/main12.jpg'>
</div>

app/views/products/edit.haml
.new_edit_form
  = form_for @product do |f|
    %div
      = f.label :title
      = f.text_field :title, :autofocus => true

    %div
      = f.label :price
      = f.text_field :price

    %div
      = f.label :size
      = f.text_field :size

    %div
      = f.label :description
      = f.text_area :description, :cols => "50", :rows => "3"

    %div
      = f.label :category
      = select_tag 'product[category_ids]', options_from_collection_for_select(Category.all, "id", "name"), :include_blank => true, :multiple => true

    %div
      = f.label :image
      = f.url_field :image

    %label
    = f.submit

app/views/products/index.haml
.show_all
  .head
    %h2 Products
  
  %ul
  - @products.each do |product|
    .inside_product
      %li= link_to product.title, product
      .special
        = link_to image_tag(product.image), product

app/views/products/new.haml
.new_edit_form
  = form_for @product do |f|
    %div
      = f.label :title
      = f.text_field :title, :autofocus => true

    %div
      = f.label :price
      = f.text_field :price

    %div
      = f.label :size
      = f.text_field :size

    %div
      = f.label :description
      = f.text_area :description, :cols => "50", :rows => "3"

    %div
      = f.label :category
      = select_tag 'product[category_ids]', options_from_collection_for_select(Category.all, "id", "name"), :include_blank => true, :multiple => true

    %div
      = f.label :image
      = f.url_field :image

    %label
    = f.submit

app/views/products/show.haml
.show_product_left
  %h2= @product.title

  .product
    = image_tag @product.image

.show_product_right
  %p
    Price:
    = number_to_currency(@product.price)

  %p
    Size:
    = @product.size

  %p
    Description:
    = @product.description

  %p
    Owner:
    = link_to(@product.user.name, @product.user)

  %p
    Category:
    %ul
    - @product.categories.each do |category|
      %li= link_to category.name, category
  
  .inside_product_1 
    - if @current_user && (@product.user.id == @current_user.id)
      .linking_button
        = link_to('Edit', edit_product_path(@product))
      .linking_button
        = link_to('Delete', @product, :method => :delete , :data => {:confirm => 'Are you sure?'})

    - if !@current_user
      = link_to('Buy', login_path)
    -else
      - if @product.user.id != @current_user.id
        %form{:action => "", :method => :post}
          %script{:src => "https://checkout.stripe.com/checkout.js", :class => "stripe-button", :"data-key" => "pk_test_1RUHmTu8c2nR2F2UPOqV1Bof", :"data-amount" => @product.price.to_f, :"data-name" => "Charisma", :"data-description" => @product.title + ' $' + @product.price.to_s, :"data-image" => @product.image}

    .linking_button
      = link_to('All items', products_path)


.comments
 
  %p
    = @product.comments.count
    Comments:
    %ul
    - @product.comments.each do |comment|
      - if comment.user
        %li
          %b
            = link_to(comment.user.name, comment.user)
          = comment.body

  - if @current_user

    = form_for ([@product, @product.comments.new]) do |f|
      %div
        
        = f.text_area :body, :cols => "80", :rows => "5", :autofocus => true

      %label
      = f.submit "comment"  

app/views/session/new.haml
.new_edit_form
  = form_tag '/login' do
    %div
      = label_tag :username
      = text_field_tag :username, nil, :autofocus => true
    %div
      = label_tag :password
      = password_field_tag :password
    
    %label
    = submit_tag 'Login'

app/views/users/edit.haml
%h2
  Editing
  = @user.name

= form_for @user do |f|
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :email
    = f.email_field :email

  %div
    = f.label :avatar
    = f.url_field :avatar

  %div
    = f.label :status
    = f.text_field :status

  %div
    = f.label :city
    = f.text_field :city

  %div
    = f.label :country
    = f.text_field :country

  = f.submit

app/views/users/index.haml
.show_all
  .head
    %h2 Our beloved users
  %ul
  - @users.each do |user|
    .inside_product
      %li= link_to user.name, user
      .special
        = image_tag user.avatar

app/views/users/new.haml
.new_edit_form
  - if @user.errors.any?
    %ol
      - @user.errors.full_messages.each do |msg|
        %li= msg

  = form_for @user do |f|
    %div
      = f.label :name
      = f.text_field :name, :autofocus => true

    %div
      = f.label :email
      = f.email_field :email

    %div
      = f.label :password
      = f.password_field :password

    %div
      = f.label :password_confirmation
      = f.password_field :password_confirmation

    %label
    = f.submit

app/views/users/show.haml
.profile_left
  %h2= @user.name
  .avatar
    = image_tag @user.avatar

  - if @user.status
    %p
      Status:
      = @user.status

  %p
    User since:
    = @user.created_at.strftime '%B %m %Y'

  - if @user.city
    %p
      Lives in:
      = @user.city + ','
      = @user.country

  - if @current_user && (@current_user.id == @user.id)
    .linking_button
      = link_to 'Add item', new_product_path
 
    .linking_button
      = link_to 'Edit profile', edit_user_path

.profile_right
  - if @user.products
    %p
      Works:
      %ul
        - @user.products.each do |product|
          %li= link_to product.title, product